### ISSUE TITLE
failed : continuously playing for youtube play list

### ISSUE THREAD

**Issue by bsplu** [c4rO-0/chromeExtPIP#1]
e.g. [youtube paly list](https://www.youtube.com/watch?v=3TGTE6sSrVE&list=RD6Yvwqtme-u8&index=3)
1. after entering PIP
2. click "next video", PIP will exit by it self. 

The play list can not be continuously played in PIP mod.
By the way, [greasyfork script ](https://greasyfork.org/en/scripts/377497-%E5%B0%8F%E7%AA%97%E5%8F%A3%E8%A7%86%E9%A2%91-bili-mgtv-youtube) works.

**Comment by l365692902** [comment]
已修
